### ISSUE TITLE
External Libraries and optimization

### ISSUE THREAD

**Issue by MykhailoDz** [WebPlatformForEmbedded/Lightning#25] opened 2019-07-26 14:15 UTC
Hello Team! 
Could you explain how can I use external libraries inside App (ex. import redux from 'redux' will give an error)?
And how can I minify and uglify code using  'npm run release-web'?
Because if I use webpack, it creates build, adding: lightning-web.js, and ux.js (like in init.js inside dist/web) and after that, this._setState doesn't work.
Please, share an example.
@thiblahute @Ms2ger @basvanmeurs @clopez @kuscsik

**Comment by erikhaandrikman** [comment] 2019-07-26 20:09
Hey! Well you should be able to import modules and use them in lightning. My next question would be, why do you want to use Redux? Lightning is by heart state driven so it has a build in statemachine. https://webplatformforembedded.github.io/Lightning/docs/components/statemachine/statemachine

**Comment by MykhailoDz** [comment] 2019-07-26 20:43
It was just an example. I mean when you import it w/o webpack, it will give an error(Relative references must start with either "/", "./", or "../) . And if create production build state doesn’t sets. @erikhaandrikman

**Comment by g-zachar** [comment] 2019-09-02 15:12
Closing it for now, please reopen if still relevant.

> Could you explain how can I use external libraries inside App (ex. import redux from 'redux' will give an error)?
And how can I minify and uglify code using 'npm run release-web'?
Because if I use webpack, it creates build, adding: lightning-web.js, and ux.js (like in init.js inside dist/web) and after that, this._setState doesn't work.
Please, share an example.

Please share your project setup so I can understand better and reproduce the issue.

> It was just an example. I mean when you import it w/o webpack, it will give an error(Relative references must start with either "/", "./", or "../) . And if create production build state doesn’t sets. 

You're encountering bare import problem which is not anything specific to lightning framework.

**Closed by g-zachar** 2019-09-02 15:12 UTC
