### ISSUE TITLE
Issue with RoundedRectangle shader

### ISSUE THREAD

**Issue by yuraantonov11** [WebPlatformForEmbedded/Lightning#73] opened 2019-11-28 18:02 UTC
Hi, after adding this code to my comonent:
```javascript
   rtt: true,
        shader: {
            type: lng.shaders.RoundedRectangle,
            radius: ROUND_RADIUS
        },
```

I have got blinking screen issue with this error:
https://drive.google.com/file/d/1leM24VeNam2XTlBiha9AcVrJldG2f2yR/view?usp=sharing

**Comment by g-zachar** [comment] 2019-11-29 09:46
Hi @yuraantonov11 

Can you provide more context to this issue? Does this happen when you use different shaders in this context aswell?

Best regards

**Comment by yuraantonov11** [comment] 2019-12-23 16:18
Hi @g-zachar, I have a carousel with cards, and after added rounded corners to the card I have this [Carousel Image.](https://drive.google.com/open?id=1orNcMPbCVKwetmyEL3IBy6WTlKXjVj68)
```javascript
            Content: {
                rtt: true,
                shader: {
                    type: lng.shaders.RoundedRectangle,
                    radius: ROUND_RADIUS
                },
```

**Comment by g-zachar** [comment] 2020-02-10 09:34
Closing for now, please reopen if it's still relevant. I couldn't reproduce the issue myself.

**Closed by g-zachar** 2020-02-10 09:34 UTC
Labels: bug
