### ISSUE TITLE
Text not rendered after state changed for the first time

### ISSUE THREAD

**Issue by skHazard** [WebPlatformForEmbedded/Lightning#58] opened 2019-10-03 17:08 UTC
Hello! 
I found an issue, when you have a container with some text at layout with flexItem prop,
and container with that text changes state for the first time (page refreshed) and then you enter that state, text is not rendered at all. And it's reproduced 100% every time.

Also I can say that there is no such issue if you remove flexItem prop.

**Comment by woutermeek** [comment] 2019-10-03 17:15
Hi @skHazard 
Could you share a small code example which reproduces the issue?
Thanks

**Comment by g-zachar** [comment] 2019-10-08 14:46
Hi @skHazard 

Are you able to provide full example? I'm not able to figure out what the problem is based on your description.

**Comment by MykhailoDz** [comment] 2019-10-30 12:11
@g-zachar We will try to create an example in the future, but for now we can share the gif :

![ezgif-1-c051e5a53373](https://user-images.githubusercontent.com/46669878/67857304-18320500-fb1f-11e9-8a13-c7ee0bd2ad4b.gif)

**Comment by woutermeek** [comment] 2019-10-30 12:24
I've put this on hold for now. Please share an example so we can look into it.

**Comment by erikhaandrikman** [comment] 2020-02-27 09:38
Closing this ticket for now

**Closed by erikhaandrikman** 2020-02-27 09:38 UTC
Labels: on hold
