### ISSUE TITLE
Get size of image before rendering

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#91] opened 2020-01-13 09:44 UTC
It is possible to obtain the size (`width`, `height`) of and image before rendering it? It should be usefull for calculating positioning and distances in a carousel.
I thinging about something like an event (es: `imageLoaded`) with an Event object containing the siezes. Then You can patch the element with correct size.
For example [here](https://github.com/WebPlatformForEmbedded/Lightning-Demo-App).
Or is better to obtain that eventually from the server?

**Comment by g-zachar** [comment] 2020-01-13 10:08
Hey @MattiaPontonioKineton,

Possible duplicate of #38 

Also, I'm not sure what your example link refers to.

Best regards

**Comment by MattiaPontonioKineton** [comment] 2020-01-13 10:49
Hi @g-zachar,

thanks for the reference.
As You can see here:
https://github.com/WebPlatformForEmbedded/Lightning-Demo-App/blob/master/src/components/Slider.js#L24
the childrens are positioned with an hardcoded value of `305` multiplied by the index.
I'm looking for a solution to not hard code this value but make them relative to the real `width` of the image. I need `height` eventually for calculating ratios.
The goal is to create a slider component that works well with different types of images.
I think this solution should works but I need to test that:
https://github.com/WebPlatformForEmbedded/Lightning/issues/38#issuecomment-527835455
Flexbox is not good because of the transition of the element that need to be scaled over the siblings.
Think the issue should be closed.

Best regards

**Closed** 2020-02-10 09:26 UTC
